#!/usr/bin/env python3
"""
Verify a previously saved proof bundle.

This script expects a proof bundle generated by `prove_verify_index.py` and
uses the existing `tensorcommitments` binding to perform verification.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

try:
    import tensorcommitments
except ImportError:
    sys.exit(
        "[ERROR] Cannot import tensorcommitments.\n"
        "Activate the right env and build bindings:\n"
        "  conda activate tilecommitments\n"
        "  cd TensorCommitment/pst_commitment_lib && maturin develop --features python --release"
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Verify a saved proof bundle JSON produced by prove_verify_index.py."
    )
    parser.add_argument(
        "--bundle",
        type=Path,
        required=True,
        help="Path to proof bundle JSON.",
    )
    return parser.parse_args()


def require_field(payload: dict, name: str):
    if name not in payload:
        sys.exit(f"[ERROR] Missing required field '{name}' in bundle.")
    return payload[name]


def main() -> None:
    args = parse_args()
    bundle_path = args.bundle.resolve()
    if not bundle_path.is_file():
        sys.exit(f"[ERROR] Bundle file not found: {bundle_path}")

    with bundle_path.open("r", encoding="utf-8") as handle:
        bundle = json.load(handle)

    num_variables = int(require_field(bundle, "num_variables"))
    degree_bound = int(require_field(bundle, "degree_bound"))
    commitment_hex = str(require_field(bundle, "commitment_hex"))
    index = list(require_field(bundle, "index"))
    value_int = int(require_field(bundle, "value_int"))
    proof_hex = list(require_field(bundle, "proof_hex"))

    wrapper = tensorcommitments.TensorCommitmentWrapper(num_variables, degree_bound)
    verified = wrapper.verify(commitment_hex, index, value_int, proof_hex)

    print("[INFO] Verify saved proof bundle")
    print(f"[INFO] Bundle:       {bundle_path}")
    print(f"[INFO] Index:        {index}")
    print(f"[INFO] Value:        {value_int}")
    print(f"[INFO] Proof elems:  {len(proof_hex)}")
    print(f"[INFO] Verified:     {verified}")

    if not verified:
        sys.exit(1)


if __name__ == "__main__":
    main()
